USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_SECTOR]    Script Date: 7/04/2026 19:22:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_SECTOR](
	[ID_NIVEL_SECTOR] [int] IDENTITY(1,1) NOT NULL,
	[SECTOR] [nvarchar](2) NOT NULL,
	[SECTOR_NOMBRE] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_NIVEL_SECTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


