USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_EJECUTORA]    Script Date: 7/04/2026 19:21:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_EJECUTORA](
	[EJECUTORA_ID] [int] IDENTITY(1,1) NOT NULL,
	[EJECUTORA] [nvarchar](6) NULL,
	[EJECUTORA_NOMBRE] [nvarchar](131) NULL,
PRIMARY KEY CLUSTERED 
(
	[EJECUTORA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


