USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_NIVEL_GOBIERNO]    Script Date: 7/04/2026 19:21:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_NIVEL_GOBIERNO](
	[NIVEL_GOBIERNO_ID] [int] IDENTITY(1,1) NOT NULL,
	[NIVEL_GOBIERNO] [nvarchar](1) NOT NULL,
	[NIVEL_GOBIERNO_NOMBRE] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NIVEL_GOBIERNO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


