USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_PLIEGO]    Script Date: 7/04/2026 19:21:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_PLIEGO](
	[PLIEGO_ID] [int] IDENTITY(1,1) NOT NULL,
	[PLIEGO] [nvarchar](3) NOT NULL,
	[PLIEGO_NOMBRE] [nvarchar](107) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PLIEGO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


