USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_GENERICA]    Script Date: 7/04/2026 19:21:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_GENERICA](
	[GENERICA_ID] [int] IDENTITY(1,1) NOT NULL,
	[GENERICA] [nvarchar](1) NULL,
	[GENERICA_NOMBRE] [nvarchar](39) NULL,
PRIMARY KEY CLUSTERED 
(
	[GENERICA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


