USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_LUGAR]    Script Date: 7/04/2026 19:21:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_LUGAR](
	[LUGAR_ID] [int] IDENTITY(1,1) NOT NULL,
	[DISTRITO] [nvarchar](35) NULL,
	[PROVINCIA] [nvarchar](25) NULL,
	[DEPARTAMENTO] [nvarchar](35) NULL,
PRIMARY KEY CLUSTERED 
(
	[LUGAR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


