USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[DIM_FECHA]    Script Date: 7/04/2026 19:21:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_FECHA](
	[FECHA_ID] [int] NOT NULL,
	[ANIO] [int] NOT NULL,
	[NUM_MES] [int] NOT NULL,
	[NOMB_MES] [varchar](20) NOT NULL,
	[NOMB_MES_CORT] [varchar](5) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FECHA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


