USE [DWH_BIGDATA]
GO

/****** Object:  Table [dbo].[FACT_GASTOS]    Script Date: 7/04/2026 19:24:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACT_GASTOS](
	[EJECUTORA_ID] [int] NULL,
	[FECHA_ID] [int] NULL,
	[GENERICA_ID] [int] NULL,
	[LUGAR_ID] [int] NULL,
	[NIVEL_GOBIERNO_ID] [int] NULL,
	[PLIEGO_ID] [int] NULL,
	[NIVEL_SECTOR_ID] [int] NULL,
	[PIA] [bigint] NULL,
	[PIM] [bigint] NULL,
	[DEVENGADO] [float] NULL,
	[GIRADO] [float] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_EJECUTORA] FOREIGN KEY([EJECUTORA_ID])
REFERENCES [dbo].[DIM_EJECUTORA] ([EJECUTORA_ID])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_EJECUTORA]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_FECHA] FOREIGN KEY([FECHA_ID])
REFERENCES [dbo].[DIM_FECHA] ([FECHA_ID])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_FECHA]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_GENERICA] FOREIGN KEY([GENERICA_ID])
REFERENCES [dbo].[DIM_GENERICA] ([GENERICA_ID])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_GENERICA]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_LUGAR] FOREIGN KEY([LUGAR_ID])
REFERENCES [dbo].[DIM_LUGAR] ([LUGAR_ID])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_LUGAR]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_NIVEL_GOBIERNO] FOREIGN KEY([NIVEL_GOBIERNO_ID])
REFERENCES [dbo].[DIM_NIVEL_GOBIERNO] ([NIVEL_GOBIERNO_ID])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_NIVEL_GOBIERNO]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_PLIEGO] FOREIGN KEY([PLIEGO_ID])
REFERENCES [dbo].[DIM_PLIEGO] ([PLIEGO_ID])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_PLIEGO]
GO

ALTER TABLE [dbo].[FACT_GASTOS]  WITH CHECK ADD  CONSTRAINT [FK_DIM_SECTOR] FOREIGN KEY([NIVEL_SECTOR_ID])
REFERENCES [dbo].[DIM_SECTOR] ([ID_NIVEL_SECTOR])
GO

ALTER TABLE [dbo].[FACT_GASTOS] CHECK CONSTRAINT [FK_DIM_SECTOR]
GO


